env: prod
storage:
  className: gp2
  size: 1G
serviceAccountName: default
solodev:
  image:
    registry: docker.io
    repository: solodev/cms
    tag: latest
    pullPolicy: Always
  cname: domain.com
  port: 9000
  protocol: TCP
  storage:
    className: efs
    size: 10G
    mount: /var/www/solodev/clients/solodev
  settings:
    debug: false
    appSecret: secret
    appUser: solodev
    appPassword: password
    dbHost: mysql
    dbName: solodev
    dbUser: solodev
    dbPassword: password
    mongoDbName: solodev_views
  pullSecret: solodev
ui:
  image:
    registry: docker.io
    repository: solodev/cms-apache
    tag: latest
    pullPolicy: IfNotPresent
  http:
    port: 80
    protocol: TCP
  https:
    port: 443
    protocol: TCP
mysql:
  image:
    registry: docker.io
    # repository: mariadb
    # tag: latest
    repository: mysql
    tag: 5.6.32
    pullPolicy: IfNotPresent
  port: 3306
  read:
    port: 3307
  settings:
mongo:
  image:
    registry: docker.io
    repository: techcto/mongo
    tag: latest
    pullPolicy: IfNotPresent
  port: 27017
  settings:
    username: solodev
    password: password
redis:
  image:
    registry: docker.io
    repository: redis
    tag: latest
    pullPolicy: IfNotPresent
  port: 6379