env: prod
storage:
  className: portworx
  size: 500M
serviceAccountName: default
solodev:
  image:
    registry: docker.io
    repository: solodev/cms
    tag: latest
    pullPolicy: Always
  cname: domain.com
  port: 9000
  protocol: TCP
  storage:
    className: portworx-shared
    size: 1G
    mount: /var/www/solodev/clients/solodev
  settings:
    debug: false
    appSecret: secret
    appUser: solodev
    appPassword: password
    dbHost: mysql
    dbName: solodev
    dbUser: solodev
    dbPassword: password
    mongoDbName: solodev_views
  pullSecret: solodev
ui:
  image:
    registry: docker.io
    repository: solodev/cms-apache
    tag: latest
    pullPolicy: IfNotPresent
  http:
    port: 80
    protocol: TCP
  https:
    port: 443
    protocol: TCP
mysql:
  image:
    registry: docker.io
    repository: mariadb
    tag: 10.3
    # repository: mysql
    # tag: latest
    pullPolicy: IfNotPresent
  port: 3306
  read:
    port: 3307
  configFiles:
    master.cnf: |
      # Apply this config only on the master.
      [mysqld]
      skip-name-resolve
      port=3306
      bind-address=0.0.0.0
      wait_timeout=90
      net_read_timeout=90
      net_write_timeout=90
      connect_timeout=90
      max_allowed_packet = 512M
      character-set-server=UTF8
      collation-server=utf8_general_ci
      [client]
      port=3306
      default-character-set=UTF8
    slave.cnf: |
      # Apply this config only on slaves.
      [mysqld]
      super-read-only
      port=3307
      bind-address=0.0.0.0
mongo:
  image:
    registry: docker.io
    repository: techcto/mongo
    tag: latest
    pullPolicy: IfNotPresent
  port: 27017
  settings:
    username: solodev
    password: password
redis:
  image:
    registry: docker.io
    repository: redis
    tag: latest
    pullPolicy: IfNotPresent
  port: 6379