env: prod
storage:
  className: gp2
  size: 5G
serviceAccountName: default
solodev:
  image:
    registry: '117940112483.dkr.ecr.us-east-1.amazonaws.com/0c908dc0-e52e-4d48-bf4c-9e883d405d92/cg-1141323769'
    repository: solodev-cms
    tag: 9.3.1-latest
    pullPolicy: Always
  domainName: domain.com
  clusterZone: domain.com
  port: 9000
  protocol: TCP
  storage:
    className: gp2
    size: 5G
    mount: /var/www/solodev/clients/solodev
  settings:
    debug: false
    appSecret: secret
    appUser: solodev
    appPassword: password
    appEmail: ''
    dbHost: mysql
    dbName: solodev
    dbUser: solodev
    dbPassword: password
    clientId: ''
    clientSecret: ''
    mongoDbName: solodev_views
    websiteUrl: ''
    websiteTheme: ''
    websiteThemeValues: ''
  pullSecret: solodev
ui:
  image:
    registry: '117940112483.dkr.ecr.us-east-1.amazonaws.com/0c908dc0-e52e-4d48-bf4c-9e883d405d92/cg-1141323769'
    repository: solodev-apache
    tag: 9.3.1-latest
    pullPolicy: IfNotPresent
  http:
    port: 80
    protocol: TCP
  https:
    port: 443
    protocol: TCP
mysql:
  image:
    registry: '117940112483.dkr.ecr.us-east-1.amazonaws.com/0c908dc0-e52e-4d48-bf4c-9e883d405d92/cg-1141323769'
    repository: mariadb
    tag: 9.3.1-latest
    pullPolicy: IfNotPresent
  port: 3306
  read:
    port: 3307
mongo:
  image:
    registry: '117940112483.dkr.ecr.us-east-1.amazonaws.com/0c908dc0-e52e-4d48-bf4c-9e883d405d92/cg-1141323769'
    repository: techcto/mongo
    tag: 9.3.1-latest
    pullPolicy: IfNotPresent
  port: 27017
  settings:
    username: solodev
    password: password
redis:
  image:
    registry: '117940112483.dkr.ecr.us-east-1.amazonaws.com/0c908dc0-e52e-4d48-bf4c-9e883d405d92/cg-1141323769'
    repository: techcto/redis
    tag: 9.3.1-latest
    pullPolicy: IfNotPresent
  port: 6379