env: prod
storage:
  className: gp2
  size: 5G
serviceAccountName: default
solodev:
  image:
    registry: "docker.io"
    repository: "solodev/cms"
    tag: latest
    pullPolicy: IfNotPresent
  clusterZone: domain.com
  port: 9000
  protocol: TCP
  storage:
    className: gp2
    size: 5G
    mount: /var/www/solodev/clients/solodev
  settings:
    debug: false
    appSecret: secret
    appUser: solodev
    appPassword: password
    appEmail: ''
    dbHost: mysql
    dbName: solodev
    dbUser: solodev
    dbPassword: password
    mongoDbName: solodev_views
    websiteUrl: ''
    websiteTheme: ''
    websiteThemeValues: ''
    cloudClientId: ''
    cloudClientSecret: ''
    cloudRedirectURI: ''
    cloudAuthorizeURL: ''
    cloudAccessToken: ''
    cloudKeySet: ''
    cloudScope: ''
    cloudApiToken: ''
    cloudResourceOwner: ''
ui:
  image:
    registry: "docker.io"
    repository: "solodev/cms-apache"
    tag: latest
  http:
    port: 8080
    protocol: TCP
  https:
    port: 443
    protocol: TCP
mysql:
  image:
    registry: '117940112483.dkr.ecr.us-east-1.amazonaws.com/0c908dc0-e52e-4d48-bf4c-9e883d405d92/cg-1141323769'
    repository: mariadb
    tag: 9.3.1-latest
    pullPolicy: IfNotPresent
  port: 3306
  read:
    port: 3307
mongo:
  image:
    registry: '117940112483.dkr.ecr.us-east-1.amazonaws.com/0c908dc0-e52e-4d48-bf4c-9e883d405d92/cg-1141323769'
    repository: techcto/mongo
    tag: 9.3.1-latest
    pullPolicy: IfNotPresent
  port: 27017
  settings:
    username: solodev
    password: password
redis:
  image:
    registry: '117940112483.dkr.ecr.us-east-1.amazonaws.com/0c908dc0-e52e-4d48-bf4c-9e883d405d92/cg-1141323769'
    repository: techcto/redis
    tag: 9.3.1-latest
    pullPolicy: IfNotPresent
  port: 6379