apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-oauth2
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: "{{ .Release.Name }}.{{ .Values.provider.domain }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-salesforce
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-oauth2-proxy
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: "{{ .Release.Name }}.{{ .Values.provider.domain }}"
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-oauth2-proxy
            port:
              number: {{ .Values.provider.port }}
  tls:
  - hosts:
    - "{{ .Release.Name }}.{{ .Values.provider.domain }}"
    secretName: {{ .Release.Name }}-tls