apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  serviceName: {{ .Release.Name }}-mysql
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mysql
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Release.Name }}-mysql
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: {{ .Release.Name }}-init-mysql
        image: {{ .Values.mysql.image.registry }}/{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}
        args:
        - --ignore-db-dir=lost+found
        env:
        - name: MYSQL_DATABASE
          value: {{ .Values.solodev.settings.dbName }}
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.solodev.settings.dbPassword }}
        - name: MYSQL_USER
          value: {{ .Values.solodev.settings.dbUser }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.solodev.settings.dbPassword }}
        command:
        - bash
        - "-c"
        - |
          set -ex
          # Generate mysql server-id from pod ordinal index.
          [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
          ordinal=${BASH_REMATCH[1]}
          echo [mysqld] > /mnt/conf.d/server-id.cnf
          # Add an offset to avoid reserved server-id=0 value.
          echo server-id=$((100 + $ordinal)) >> /mnt/conf.d/server-id.cnf
          # Copy appropriate conf.d files from config-map to emptyDir.
          if [[ $ordinal -eq 0 ]]; then
            cp /mnt/config-map/master.cnf /mnt/conf.d/
          else
            cp /mnt/config-map/slave.cnf /mnt/conf.d/
          fi
        volumeMounts:
        - name: conf
          mountPath: /mnt/conf.d
        - name: config-map
          mountPath: /mnt/config-map
      containers:
      - name: {{ .Release.Name }}-mysql
        image: {{ .Values.mysql.image.registry }}/{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}
        args:
        - --sql_mode=
        - --ignore-db-dir=lost+found
        env:
        - name: MYSQL_DATABASE
          value: {{ .Values.solodev.settings.dbName }}
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.solodev.settings.dbPassword }}
        - name: MYSQL_USER
          value: {{ .Values.solodev.settings.dbUser }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.solodev.settings.dbPassword }}
        ports:
        - name: mysql
          containerPort: {{ .Values.mysql.port }}
        volumeMounts:
        - name: {{ .Release.Name }}-pv
          mountPath: /var/lib/mysql
        - name: conf
          mountPath: /etc/mysql/conf.d
        resources:
          requests:
            memory: 128M
            cpu: 50m
          limits:
            memory: 512M
            cpu: 200m
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command: ["mysql", "-h", "127.0.0.1", "-u", "root", "-p{{ .Values.solodev.settings.dbPassword }}", "-e", "SELECT 1"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: conf
        emptyDir: {}
      - name: config-map
        configMap:
          name: {{ .Release.Name }}-mysql
      - name: {{ .Release.Name }}-pv
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-mysql