apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    app: {{ .Release.Name }}-ui
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ui
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ui
    spec:
      imagePullSecrets:
      - name: {{ .Values.solodev.pullSecret }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Release.Name }}-ui
            topologyKey: "kubernetes.io/hostname"
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Release.Name }}-redis
            topologyKey: "kubernetes.io/hostname"
      containers:
      - env:
        - name: APP_ENV
          value: {{ .Values.env }}
        - name: APP_URL
          value: "{{ .Release.Name }}-solodev:{{ .Values.solodev.port }}"
        image: {{ .Values.ui.image.registry }}/{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}
        name: {{ .Release.Name }}-ui
        ports:
        - containerPort: {{ .Values.ui.http.port }}
        - containerPort: {{ .Values.ui.https.port }}
        resources: {}
        volumeMounts:
        - mountPath: {{ quote .Values.solodev.storage.mount }}
          name: client
        resources:
          requests:
            memory: 8M
            cpu: 5m
            # ephemeral-storage: 100M
          limits:
            memory: 16M
            cpu: 20m
            # ephemeral-storage: 500M
      restartPolicy: Always
      volumes:
      - name: client
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-www
