apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ui
  annotations:
    host: "{{ .Release.Name }}.{{ .Values.solodev.cname }}"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  # tls:
  # - hosts:
  #   - anthonycornell.com
  #   secretName: tls-secret
  rules:
  - host: {{ .Release.Name }}.{{ .Values.solodev.cname }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-ui
            servicePort: {{ .Values.ui.http.port }}
