apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ui
  annotations:
    host: "{{ .Release.Name }}.{{ .Values.solodev.clusterZone }}"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/service-upstream: "true"
    # ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/upstream-vhost: "{{ .Release.Name }}.{{ .Values.solodev.clusterZone }}"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      chunked_transfer_encoding off;
      proxy_max_temp_file_size 0;
spec:
  # tls:
  # - hosts:
  #   - anthonycornell.com
  #   secretName: tls-secret
  rules:
  - host: {{ .Release.Name }}.{{ .Values.solodev.clusterZone }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-ui
            servicePort: {{ .Values.ui.http.port }}
  - host: {{ .Release.Name }}.{{ .Values.solodev.domainName }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-ui
            servicePort: {{ .Values.ui.http.port }}

