# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{ .Release.Name }}-db
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: {{ .Values.storage.size }}
#   storageClassName: {{ .Values.storage.className }}
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{ .Release.Name }}-www
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: {{ .Values.solodev.storage.size }}
#   storageClassName: {{ .Values.solodev.storage.className }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-client
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.solodev.storage.size }}
  storageClassName: {{ .Values.solodev.storage.className }}