apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pv
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.className }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-client
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.solodev.storage.size }}
  storageClassName: {{ .Values.solodev.storage.className }}