apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-nextjs
  name: {{ .Release.Name }}-nextjs
spec:
  ports:
  - name: "app"
    port: {{ .Values.nextjs.port }}
    targetPort: {{ .Values.nextjs.port }}
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-nextjs
