apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nextjs
  labels:
    app: {{ .Release.Name }}-nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nextjs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nextjs
    spec:
      imagePullSecrets:
          - name: {{ .Values.nextjs.pullSecret }}
      containers:
        - name: {{ .Release.Name }}-nextjs
          image: {{ .Values.nextjs.image.registry }}/{{ .Values.nextjs.image.repository }}:{{ .Values.nextjs.image.tag }}
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: {{ quote .Values.env }}
            - name: CLOUD_CLIENT_ID
              value: {{ quote .Values.nextjs.settings.cloudClientId }}
            - name: CLOUD_CLIENT_SECRET
              value: {{ quote .Values.nextjs.settings.cloudClientSecret }}
          ports:
            - containerPort: {{ .Values.nextjs.port }}
          tty: true
          resources:
            requests:
              memory: 128M
              cpu: 100m
            limits:
              memory: 500M
              cpu: 1
      restartPolicy: Always
