# Declare variables to be passed into your templates.
jobs:
  ### REQUIRED ###
  - name: emailcenter
    image:
      registry: docker.io
      repository: solodev/cms
      tag: latest
      imagePullPolicy: Always
    pullSecret: solodev
    schedule: "*/5 * * * *"
    command: ["/bin/sh"]
    args:
      - -c
      - date; echo "hello";
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    volumeMounts:
    - name: client
      mountPath: /var/www
      subPath: client
    volumes:
    - name: client
      persistentVolumeClaim:
        claimName: client