apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-mongo
  name: {{ .Release.Name }}-mongo
spec:
  ports:
  - name: "mongo"
    port: {{ .Values.mongo.port }}
    targetPort: {{ .Values.mongo.port }}
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-mongo
