apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-solodev
  name: {{ .Release.Name }}-solodev
spec:
  ports:
  - name: "solodev"
    port: {{ .Values.solodev.port }}
    targetPort: {{ .Values.solodev.port }}
  selector:
    app: {{ .Release.Name }}-solodev
