apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    app: {{ .Release.Name }}-ui
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ports:
  - name: "http"
    port: {{ .Values.ui.http.port }}
    targetPort: 80
  - name: "https"
    port: {{ .Values.ui.https.port }}
    targetPort: 443
  selector:
    app: {{ .Release.Name }}-ui
  type: LoadBalancer