env: prod
storage:
  className: gp2 
  size: 10G
serviceAccountName: aws-serviceaccount
wordpress:
  image:
    registry: docker.io
    repository: solodev/wordpress
    tag: latest
    pullPolicy: Always
  port: 9000
  protocol: TCP
  storage:
    className: gp2
    size: 10G
    mount: /var/www/html
  settings:
    debug: false
    dbHost: mysql
    dbName: wordpress
    dbUser: wordpress
    dbPassword: password
ui:
  image:
    registry: docker.io
    repository: solodev/wordpress-proxy
    tag: latest
    pullPolicy: IfNotPresent
  http:
    port: 80
    protocol: TCP
  https:
    port: 443
    protocol: TCP
mysql:
  image:
    registry: 117940112483.dkr.ecr.us-east-1.amazonaws.com/0c908dc0-e52e-4d48-bf4c-9e883d405d92/cg-1018795255
    repository: mariadb
    tag: 9.2.1-latest
    pullPolicy: IfNotPresent
  port: 3306
  read:
    port: 3307
mongo:
  image:
    registry: 117940112483.dkr.ecr.us-east-1.amazonaws.com/0c908dc0-e52e-4d48-bf4c-9e883d405d92/cg-1018795255
    repository: techcto/mongo
    tag: 9.2.1-latest
    pullPolicy: IfNotPresent
  port: 27017
  settings:
    username: wordpress
    password: password
redis:
  image:
    registry: 117940112483.dkr.ecr.us-east-1.amazonaws.com/0c908dc0-e52e-4d48-bf4c-9e883d405d92/cg-1018795255
    repository: techcto/redis
    tag: 9.2.1-latest
    pullPolicy: IfNotPresent
  port: 6379