apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-solodev
  labels:
    app: {{ .Release.Name }}-solodev
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-solodev
    spec:
      imagePullSecrets:
      - name: {{ .Values.solodev.pullSecret }}
      containers:
      - name: {{ .Release.Name }}-solodev
        image: {{ .Values.solodev.image.repository }}:{{ .Values.solodev.image.tag }}
        env:
        - name: APP_DEBUG
          value: {{ quote .Values.solodev.settings.debug }}
        - name: APP_ENV
          value: {{ quote .Values.env }}
        - name: APP_SECRET
          value: {{ quote .Values.solodev.settings.appSecret }}
        - name: APP_URL
          value: "{{ .Release.Name }}-solodev:{{ .Values.solodev.port }}"
        - name: DB_HOST
          value: {{ .Release.Name }}-{{ .Values.solodev.settings.dbHost }}
        - name: DB_NAME
          value: {{ quote .Values.solodev.settings.dbName }}
        - name: DB_PASSWORD
          value: {{ quote .Values.solodev.settings.dbPassword }}
        - name: DB_USER
          value: {{ quote .Values.solodev.settings.dbUser }}
        - name: MONGO_HOST
          value: "{{ .Release.Name }}-mongo:{{ .Values.mongo.port }}"
        - name: REDIS_HOST
          value: "{{ .Release.Name }}-redis:{{ .Values.redis.port }}"
        - name: SOLODEV_PASSWORD
          value: {{ quote .Values.solodev.settings.appPassword }}
        - name: SOLODEV_USER
          value: {{ quote .Values.solodev.settings.appUser }}
        - name: WEBSITE_URL
          value: {{ quote .Values.solodev.migration.WEBSITE_URL }}
        - name: WEBSITE_NAME
          value: {{ quote .Values.solodev.migration.WEBSITE_NAME }}
        - name: WEBSITE_NUMBER
          value: {{ quote .Values.solodev.migration.WEBSITE_NUMBER }}
        - name: WEBSITE_ADMIN
          value: {{ quote .Values.solodev.migration.WEBSITE_ADMIN }}
        - name: BLOG_ID
          value: {{ quote .Values.solodev.migration.BLOG_ID }}
        - name: BLOG_ID_OLD
          value: {{ quote .Values.solodev.migration.BLOG_ID_OLD }}
        ports:
        - containerPort: {{ .Values.solodev.port }}
        resources: {}
        tty: true
        volumeMounts:
        - mountPath: {{ quote .Values.solodev.storage.mount }}
          name: client
      restartPolicy: Always
      volumes:
      - name: client
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-client
