apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.ssl.email }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    # this solver uses ambient credentials (i.e. inferred from the environment or EC2 Metadata Service)
    - selector:
        dnsZones:
          - "{{ .Values.dns.zone.name }}"
      dns01:
        route53:
          region: us-east-1
          hostedZoneID: {{ .Values.dns.zone.id }} 