apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    ...
    solvers:
    # example: cross-account zone management for example.com
    # this solver uses ambient credentials (i.e. inferred from the environment or EC2 Metadata Service)
    # to assume a role in a different account
    - selector:
        dnsZones:
          - "{{ .Values.dns.zone.name }}"
      dns01:
        route53:
          region: us-east-1
          hostedZoneID: {{ .Values.dns.zone.id }} # optional, see bpolicy above
          # role: arn:aws:iam::XXXXXXXXXXXX:role/dns-manager

    # this solver handles foobar.cloud challenges
    # and uses explicit credentials
    # - selector:
    #     dnsZones:
    #       - "foobar.cloud"
    #   dns01:
    #     route53:
    #       region: eu-central-1
    #       accessKeyID: AKIAIOSFODNN7EXAMPLE
    #       secretAccessKeySecretRef:
    #         name: prod-route53-credentials-secret
    #         key: secret-access-key
    #       # you can also assume a role with these credentials
    #       role: arn:aws:iam::XXXXXXXXXXXX:role/dns-manager