apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-3
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  priority_io: "high"
  io_profile: "db"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-2
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  priority_io: "high"
  io_profile: "db"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
  priority_io: "high"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-shared
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
  priority_io: "high"
  shared: "true"
  sharedv4: "true"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
parameters:
  fsType: ext4
  type: gp2
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebsx
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
parameters:
  fsType: xfs
  type: gp2
