apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-repl3
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  priority_io: "high"
  snapshotschedule.stork.libopenstorage.org/default-schedule: |
    schedulePolicyName: daily
    annotations:
      portworx/snapshot-type: local
  snapshotschedule.stork.libopenstorage.org/weekly-schedule: |
    schedulePolicyName: weekly
    annotations:
      portworx/snapshot-type: cloud
      # https://docs.portworx.com/reference/cli/credentials/#list-credentials
      # portworx/cloud-cred-id: <credential-uuid>
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-repl2
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  priority_io: "high"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
  priority_io: "high"