apiVersion: stork.libopenstorage.org/v1alpha1
kind: SchedulePolicy
metadata:
  name: daily
policy:
  daily:
    time: "10:14PM"
    retain: 3
---
apiVersion: stork.libopenstorage.org/v1alpha1
kind: SchedulePolicy
metadata:
  name: weekly
policy:
  weekly:
    day: "Thursday"
    time: "10:13PM"
    retain: 2