apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-repl3
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  priority_io: "high"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-repl2
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  priority_io: "high"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
  priority_io: "high"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-shared
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
  priority_io: "high"
  shared: "true"