apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-ocoa
  name: {{ .Release.Name }}-ocoa
spec:
  ports:
  - name: "app"
    port: {{ .Values.ocoa.port }}
    targetPort: {{ .Values.ocoa.port }}
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-ocoa
