apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-fs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ocoa.storage.size }}
  storageClassName: {{ .Values.ocoa.storage.className }}
