apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-client
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.wordpress.storage.size }}
  storageClassName: {{ .Values.wordpress.storage.className }}
