apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-wordpress
  name: {{ .Release.Name }}-wordpress
spec:
  ports:
  - name: "wordpress"
    port: {{ .Values.wordpress.port }}
    targetPort: {{ .Values.wordpress.port }}
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-wordpress
