apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordpress
  labels:
    app: {{ .Release.Name }}-wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-wordpress
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      imagePullSecrets:
      - name: {{ .Values.wordpress.pullSecret }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Release.Name }}-wordpress
            topologyKey: "kubernetes.io/hostname"
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Release.Name }}-mysql
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: {{ .Release.Name }}-wordpress
        image: {{ .Values.wordpress.image.registry }}/{{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag }}
        imagePullPolicy: Always
        env:
        - name: APP_DEBUG
          value: {{ quote .Values.wordpress.settings.debug }}
        - name: APP_ENV
          value: {{ quote .Values.env }}
        - name: APP_URL
          value: "{{ .Release.Name }}-wordpress:{{ .Values.wordpress.port }}"
        - name: WORDPRESS_DB_HOST
          value: {{ .Release.Name }}-{{ .Values.wordpress.settings.dbHost }}
        - name: WORDPRESS_DB_NAME
          value: {{ quote .Values.wordpress.settings.dbName }}
        - name: WORDPRESS_DB_PASSWORD
          value: {{ quote .Values.wordpress.settings.dbPassword }}
        - name: WORDPRESS_DB_USER
          value: {{ quote .Values.wordpress.settings.dbUser }}
        - name: WORDPRESS_ADMIN_PASSWORD
          value: {{ quote .Values.wordpress.settings.appPassword }}
        - name: WORDPRESS_ADMIN_USER
          value: {{ quote .Values.wordpress.settings.appUser }}
        - name: WORDPRESS_ADMIN_EMAIL
          value: {{ quote .Values.wordpress.settings.appEmail }}
        - name: WORDPRESS_WEBSITE_URL
          value: {{ quote .Values.wordpress.settings.websiteUrl }}
        ports:
        - containerPort: {{ .Values.wordpress.port }}
        resources: {}
        tty: true
        volumeMounts:
        - name: client
          mountPath: {{ quote .Values.wordpress.storage.mount }}
          subPath: client
        resources:
          requests:
            memory: 128M
            cpu: 100m
          limits:
            memory: 1G
            cpu: 1
      restartPolicy: Always
      volumes:
      - name: client
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-client
