apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ocoa
  labels:
    app: {{ .Release.Name }}-ocoa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ocoa
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ocoa
    spec:
      imagePullSecrets:
      - name: {{ .Values.ocoa.pullSecret }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Release.Name }}-ocoa
            topologyKey: "kubernetes.io/hostname"
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Release.Name }}-redis
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: {{ .Release.Name }}-ocoa
        image: {{ .Values.ocoa.image.registry }}/{{ .Values.ocoa.image.repository }}:{{ .Values.ocoa.image.tag }}
        imagePullPolicy: Always
        env:
        - name: APP_DEBUG
          value: {{ quote .Values.ocoa.settings.debug }}
        - name: APP_ENV
          value: {{ quote .Values.env }}
        - name: APP_SECRET
          value: {{ quote .Values.ocoa.settings.appSecret }}
        - name: APP_URL
          value: {{ .Release.Name }}-ocoa:{{ .Values.ocoa.port }}
        - name: DATABASE_URL
          value: mysql://{{ .Values.ocoa.settings.dbUser }}:{{ .Values.ocoa.settings.dbPassword }}@{{ .Release.Name }}-{{ .Values.ocoa.settings.dbHost }}:{{ .Values.mysql.port }}/{{ .Values.ocoa.settings.dbName }}
        - name: MYSQL_PORT
          value: {{ quote .Values.mysql.port }}
        - name: MYSQL_HOST
          value: {{ .Release.Name }}-{{ .Values.ocoa.settings.dbHost }}
        - name: MYSQL_DATABASE
          value: {{ quote .Values.ocoa.settings.dbName }}
        - name: MYSQL_PASSWORD
          value: {{ quote .Values.ocoa.settings.dbPassword }}
        - name: MYSQL_USER
          value: {{ quote .Values.ocoa.settings.dbUser }}
        - name: REDIS_HOST
          value: {{ .Release.Name }}-redis:{{ .Values.redis.port }}
        - name: CLOUD_CLIENT_ID
          value: {{ quote .Values.ocoa.settings.cloudClientId }}
        - name: CLOUD_CLIENT_SECRET
          value: {{ quote .Values.ocoa.settings.cloudClientSecret }}
        - name: CLOUD_REDIRECT_URI
          value: {{ quote .Values.ocoa.settings.cloudRedirectURI }}
        - name: CLOUD_AUTHORIZE_URL
          value: {{ quote .Values.ocoa.settings.cloudAuthorizeURL }}
        - name: CLOUD_ACCESS_TOKEN
          value: {{ quote .Values.ocoa.settings.cloudAccessToken }}
        - name: CLOUD_KEY_SET
          value: {{ quote .Values.ocoa.settings.cloudKeySet }}
        - name: CLOUD_SCOPE
          value: {{ quote .Values.ocoa.settings.cloudScope }}
        - name: CLOUD_API_TOKEN
          value: {{ quote .Values.ocoa.settings.cloudApiToken }}
        - name: CLOUD_RESOURCE_OWNER
          value: {{ quote .Values.ocoa.settings.cloudResourceOwner }}
        ports:
        - containerPort: {{ .Values.ocoa.port }}
        resources: {}
        tty: true
        volumeMounts:
        - name: fs
          mountPath: {{ quote .Values.ocoa.storage.mount }}
          subPath: fs
        resources:
          requests:
            memory: 128M
            cpu: 100m
          limits:
            memory: 1G
            cpu: 1
      restartPolicy: Always
      volumes:
      - name: fs
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-fs
