apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    app: {{ .Release.Name }}-ui
spec:
  ports:
  - name: "http"
    port: {{ .Values.ui.http.port }}
    targetPort: 8080
  - name: "https"
    port: {{ .Values.ui.https.port }}
    targetPort: 443
  externalName: {{ .Release.Name }}-ui
  # clusterIP: None
  selector:
    app: {{ .Release.Name }}-ui