apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    app: {{ .Release.Name }}-ui
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ui
    spec:
      imagePullSecrets:
      - name: {{ .Values.solodev.pullSecret }}
      containers:
      - env:
        - name: APP_ENV
          value: {{ .Values.env }}
        - name: APP_URL
          value: "{{ .Release.Name }}-solodev:{{ .Values.solodev.port }}"
        image: {{ .Values.ui.image.registry }}/{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}
        name: {{ .Release.Name }}-ui
        ports:
        - containerPort: {{ .Values.ui.http.port }}
        - containerPort: {{ .Values.ui.https.port }}
        resources: {}
        volumeMounts:
        # - mountPath: {{ quote .Values.solodev.storage.mount }}
        #   name: client
        - name:  {{ .Release.Name }}-pv
          mountPath: {{ quote .Values.solodev.storage.mount }}
          subPath: client
      restartPolicy: Always
      # volumes:
      # - name: client
      #   persistentVolumeClaim:
      #     claimName: {{ .Release.Name }}-client
      volumes:
      - name:  {{ .Release.Name }}-pv
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pv
